name       : kompare
version    : 22.08.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kompare-22.08.3.tar.xz : db058323d3d94d3d61cb31bae5e89fe26e2d6b76e64225fac632b01c45408978
homepage   : https://kde.org/applications/development/org.kde.kompare
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - kdoctools-devel
    - kiconthemes-devel
    - kparts-devel
    - ktexteditor-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
