name       : kompare
version    : 18.12.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kompare-18.12.0.tar.xz : a4dff51fedc1aead396f1017c5dd115f98998e1b1176f7fd7a708f4f99a2c409
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kjobwidgets-devel
    - kparts-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
