name       : kompare
version    : 18.08.2
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kompare-18.08.2.tar.xz : 69d822d3f2c4c6d7babdcea153aa465a9bb990e465a19d3c451ad6a78fc2249e
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kjobwidgets-devel
    - kparts-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
