name       : kompare
version    : 20.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kompare-20.08.1.tar.xz : 6e9109f1b24b3d79dec3d70c75357a67d16ab35081bcf7e4b842981b84796aa2
homepage   : https://kde.org/applications/development/org.kde.kompare
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - kiconthemes-devel
    - kjobwidgets-devel
    - kparts-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
