name       : kompare
version    : 18.12.2
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kompare-18.12.2.tar.xz : 39bb184ada4147081ab8859dde63565b4a1c1dc555c0e3ec2fa5f53bf49d3002
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kjobwidgets-devel
    - kparts-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
