name       : kompare
version    : 22.04.1
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kompare-22.04.1.tar.xz : 15fc7e13926dd0a994f50edc5b4ff17d7564f2f0781598a2106f6edb8bac534e
homepage   : https://kde.org/applications/development/org.kde.kompare
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : File Comparator
description: |
    Tool to visualize changes between two versions of a file.
builddeps  :
    - kdoctools-devel
    - kiconthemes-devel
    - kparts-devel
    - ktexteditor-devel
    - libkomparediff2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
